date.timezone=UTC
display_errors=On
error_reporting=E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
log_errors=On
memory_limit=512M
max_execution_time=120
post_max_size=64M
upload_max_filesize=64M
variables_order=EGPCS
opcache.enable=1
opcache.validate_timestamps=1
session.cookie_httponly=1
session.cookie_samesite=Lax
