[globals]

[default]
exten => _X.,1,Goto(a2billingplus-sandbox,${EXTEN},1)

[a2billingplus-sandbox]
exten => _X.,1,NoOp(A2BillingPlus sandbox call to ${EXTEN})
 same => n,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()

exten => 1000,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
