[global]
type=global
user_agent=A2BillingPlus Sandbox

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[sandbox-endpoint]
type=endpoint
context=a2billingplus-sandbox
disallow=all
allow=ulaw,alaw
auth=sandbox-auth
aors=sandbox-aor
direct_media=no

[sandbox-auth]
type=auth
auth_type=userpass
username=1001
password=1001

[sandbox-aor]
type=aor
max_contacts=1
