[globals]

[default]
exten => _X.,1,Goto(a2billingplus-sandbox,${EXTEN},1)

[from-pstn]
exten => s,1,NoOp(Inbound PSTN call without URI user)
 same => n,AGI(a2billing/a2billing.php,1,did)
 same => n,Hangup()

exten => _+X.,1,NoOp(Inbound PSTN DID call to ${EXTEN})
 same => n,AGI(a2billing/a2billing.php,1,did)
 same => n,Hangup()

exten => _X.,1,NoOp(Inbound PSTN DID call to ${EXTEN})
 same => n,AGI(a2billing/a2billing.php,1,did)
 same => n,Hangup()

[a2billingplus-sandbox]
exten => _X.,1,NoOp(A2BillingPlus sandbox call to ${EXTEN})
 same => n,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()

exten => 1000,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
