ALTER TABLE ps_auths
    ADD COLUMN IF NOT EXISTS realm VARCHAR(255) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS md5_cred VARCHAR(40) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS nonce_lifetime INT DEFAULT NULL;

ALTER TABLE ps_aors
    ADD COLUMN IF NOT EXISTS qualify_frequency INT NOT NULL DEFAULT 60,
    ADD COLUMN IF NOT EXISTS authenticate_qualify VARCHAR(3) NOT NULL DEFAULT 'no',
    ADD COLUMN IF NOT EXISTS default_expiration INT NOT NULL DEFAULT 3600,
    ADD COLUMN IF NOT EXISTS maximum_expiration INT NOT NULL DEFAULT 7200,
    ADD COLUMN IF NOT EXISTS minimum_expiration INT NOT NULL DEFAULT 60;

ALTER TABLE ps_endpoints
    ADD COLUMN IF NOT EXISTS callerid VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS dtmf_mode VARCHAR(20) NOT NULL DEFAULT 'rfc4733',
    ADD COLUMN IF NOT EXISTS language VARCHAR(20) NOT NULL DEFAULT 'en',
    ADD COLUMN IF NOT EXISTS mailboxes VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS moh_suggest VARCHAR(80) NOT NULL DEFAULT 'default',
    ADD COLUMN IF NOT EXISTS from_user VARCHAR(80) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS from_domain VARCHAR(120) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS outbound_proxy VARCHAR(255) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS rtp_keepalive INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rtp_timeout INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS rtp_timeout_hold INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS send_rpid VARCHAR(3) NOT NULL DEFAULT 'no',
    ADD COLUMN IF NOT EXISTS trust_id_inbound VARCHAR(3) NOT NULL DEFAULT 'no',
    ADD COLUMN IF NOT EXISTS trust_id_outbound VARCHAR(3) NOT NULL DEFAULT 'no',
    ADD COLUMN IF NOT EXISTS allow_transfer VARCHAR(3) NOT NULL DEFAULT 'yes',
    ADD COLUMN IF NOT EXISTS set_var VARCHAR(255) NOT NULL DEFAULT '';

UPDATE ps_aors
SET qualify_frequency = 60
WHERE qualify_frequency IS NULL OR qualify_frequency = 0;

UPDATE ps_endpoints
SET dtmf_mode = 'rfc4733'
WHERE COALESCE(dtmf_mode, '') = '';

UPDATE ps_endpoints
SET language = 'en'
WHERE COALESCE(language, '') = '';

UPDATE ps_endpoints
SET moh_suggest = 'default'
WHERE COALESCE(moh_suggest, '') = '';
