CREATE TABLE IF NOT EXISTS cc_vectavoip_installations (
    id BIGINT NOT NULL AUTO_INCREMENT,
    installation_id VARCHAR(64) NOT NULL,
    install_key VARCHAR(128) NOT NULL,
    api_key VARCHAR(128) NOT NULL,
    api_secret_hash VARCHAR(128) NOT NULL,
    company_name VARCHAR(191) NOT NULL,
    company_domain VARCHAR(191) NOT NULL,
    contact_name VARCHAR(191) NOT NULL,
    contact_email VARCHAR(191) NOT NULL,
    contact_phone VARCHAR(64) NOT NULL DEFAULT '',
    details TEXT NULL,
    app_name VARCHAR(128) NOT NULL,
    app_version VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    metadata_json TEXT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    last_seen_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_vectavoip_installation_id (installation_id),
    UNIQUE KEY uniq_vectavoip_install_key (install_key),
    UNIQUE KEY uniq_vectavoip_api_key (api_key),
    KEY idx_vectavoip_contact_email (contact_email),
    KEY idx_vectavoip_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
