ALTER TABLE cc_sip_buddies
    MODIFY name varchar(80) NOT NULL DEFAULT '',
    MODIFY accountcode varchar(20) NOT NULL DEFAULT '',
    MODIFY regexten varchar(20) NOT NULL DEFAULT '',
    MODIFY callerid varchar(80) NOT NULL DEFAULT '',
    MODIFY context varchar(80) NOT NULL DEFAULT '',
    MODIFY fromuser varchar(80) NOT NULL DEFAULT '',
    MODIFY fromdomain varchar(80) NOT NULL DEFAULT '',
    MODIFY host varchar(50) NOT NULL DEFAULT '',
    MODIFY insecure varchar(20) NOT NULL DEFAULT '',
    MODIFY mailbox varchar(50) NOT NULL DEFAULT '',
    MODIFY md5secret varchar(80) NOT NULL DEFAULT '',
    MODIFY deny varchar(95) NOT NULL DEFAULT '',
    MODIFY mask varchar(95) NOT NULL DEFAULT '',
    MODIFY secret varchar(80) NOT NULL DEFAULT '',
    MODIFY username varchar(80) NOT NULL DEFAULT '',
    MODIFY allow varchar(100) NOT NULL DEFAULT '',
    MODIFY musiconhold varchar(100) NOT NULL DEFAULT '',
    MODIFY fullcontact varchar(80) NOT NULL DEFAULT '',
    MODIFY setvar varchar(100) NOT NULL DEFAULT '';

ALTER TABLE cc_iax_buddies
    MODIFY name varchar(80) NOT NULL DEFAULT '',
    MODIFY accountcode varchar(20) NOT NULL DEFAULT '',
    MODIFY regexten varchar(20) NOT NULL DEFAULT '',
    MODIFY callerid varchar(80) NOT NULL DEFAULT '',
    MODIFY context varchar(80) NOT NULL DEFAULT '',
    MODIFY host varchar(50) NOT NULL DEFAULT '',
    MODIFY deny varchar(95) NOT NULL DEFAULT '',
    MODIFY mask varchar(95) NOT NULL DEFAULT '',
    MODIFY secret varchar(80) NOT NULL DEFAULT '',
    MODIFY username varchar(80) NOT NULL DEFAULT '',
    MODIFY disallow varchar(100) NOT NULL DEFAULT '',
    MODIFY allow varchar(100) NOT NULL DEFAULT '';
